### PR TITLE
📥 Patch suggestion, adding trading API as envVars

### PR DESCRIPTION
**Pull request by CatScan-crypt**
Please note that this is only a part of the patch and not meant to be merged.

The purpose of this example is to show the first step in a PR that:
Creates a seamless transition between stage API and the live API.

Extra steps:
1).
patch:   ./helpers/loadFromEnvOrConfig .
with:  API: getConfigVar('API', config) .

2).
patch:   every file in " ./examples "   that uses the API.
with:
 a) const api = envVars.API
 b) const dvfConfig = { api: api}

This is how i use to change the platform state with ease.
If it's something you would like to use just approve and i will create a
new PR with all the steps bundled.

### CODE REVIEW

**Comment by plutoegg** [comment]
This definitely seems like a good suggestion to me, thanks @CatScan-crypt 

We can update our examples along these lines, or feel free to also create a new PR doing this. @thiagokroger perhaps take a look as well?

**Comment by thiagokroger** [comment]
I think this is a good idea!

**Comment by CatScan-crypt** [comment]
done

**Comment by AliMeer** [comment]
@CatScan-crypt Examples are created by using the build examples script under helpers folder.

The content of the examples should be edited in examples/src and then the actual examples generated by running https://github.com/DeversiFi/dvf-client-js/blob/master/examples/helpers/buildExamples.js

The boilerplate common to all examples is in https://github.com/DeversiFi/dvf-client-js/blob/master/examples/helpers/example.js.tmpl

The list/order of examples to be compiled is in https://github.com/DeversiFi/dvf-client-js/blob/master/examples/helpers/examplesList.js (so the new example will need to be added there)

**Comment by adrian-gierakowski** [comment]
@CatScan-crypt than you for your contribution, however since the comment above has not been addressed for a while I am closing this PR in favour of: #131

**Pull request closed without merging**
