### PR TITLE
feat: register with contract wallet address

### PR DESCRIPTION
**Pull request by thiagokroger**

### CODE REVIEW

**Comment by thiagokroger** [comment]
@Matko95 @konradstrachan @plutoegg

**Review by Matko95 — COMMENTED** [review]
I'm not fully aware of how this argument works and if it's optional. 
In case it's supposed to be optional, we can use a pattern like this `...(value && { value })`, so we don't send contractWalletAddress as undefined or something unexpected to the backend.

**Comment by thiagokroger** [comment]
> I'm not fully aware of how this argument works and if it's optional.
> In case it's supposed to be optional, we can use a pattern like this `...(value && { value })` when adding it to the request data, so we don't send contractWalletAddress as undefined or something unexpected to the backend.

@Matko95 good point, you are right.
I just pushed a fix

**Review by Matko95 — APPROVED** [review]

**Comment by thiagokroger** [comment]
@Matko95 @plutoegg can anyone merge it?
I don't think I can

image

**Pull request merged**
