### PR TITLE
cleanup/upgrade deps

### PR DESCRIPTION
**Pull request by adrian-gierakowski**
many deps where unused or outdated
and some dev-deps included in deps

### CODE REVIEW

**Comment by adrian-gierakowski** [comment]
@Matko95 some of the dev-deps used to in scripts for building the browser version (I guess) are still a few major version behind but I did not want to touch them since I have no good way of checking if the functionality they are used for would break

**Comment by adrian-gierakowski** [comment]
a couple of tests are failing but those are the same which are failing on dev

**Comment by plutoegg** [comment]
My only concern here is the upgrade of web3 version - it occasionally has some strange breaking changes / bugs in versions @Matko95 i'll leave it to you to confirm this is fine with the updated web3 version before merging

**Review by plutoegg — APPROVED** [review]

**Comment by Matko95** [comment]
I'm going to have to test out this branch locally to confirm

**Comment by adrian-gierakowski** [comment]
@Matko95 
> I'm going to have to test out this branch locally to confirm

thanks!

**Comment by adrian-gierakowski** [comment]
superseded by #138

**Pull request closed without merging**
