### PR TITLE
contract: adding BridgeDepositContract ABI

### PR DESCRIPTION
**Pull request by Neozaru**
Related to https://app.asana.com/0/1165477653959782/1200348965543099/f

### CODE REVIEW

**Review by arijoon — APPROVED** [review]

**Comment by arijoon** [comment]
Do we also need a wrapper interface for the contract?

**Comment by Neozaru** [comment]
> Do we also need a wrapper interface for the contract?

Do you mean shortcut functions for contract calls ?

**Comment by arijoon** [comment]
> > Do we also need a wrapper interface for the contract?
> 
> Do you mean shortcut functions for contract calls ?

contract calls, and possibly shortcut functions if multiple calls can be grouped

**Comment by Neozaru** [comment]
> > > Do we also need a wrapper interface for the contract?
> > 
> > 
> > Do you mean shortcut functions for contract calls ?
> 
> contract calls, and possibly shortcut functions if multiple calls can be grouped

So definitely yes but I think I will create those as part of the UI changes. This PR is mostly preparing the terrain for the backend to access to the ABI - and for now the backend is forging signed txs without using shortcut functions

**Pull request merged**
